# Generated by Django 4.2.7 on 2023-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideos',
            name='violent',
            field=models.BooleanField(default=False),
        ),
    ]
