# Generated by Django 4.2.7 on 2024-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_customuser_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideos',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
