# Generated by Django 4.2.7 on 2024-01-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_uploadedvideos_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideos',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
