# Generated by Django 4.2.7 on 2024-01-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_uploadedvideos_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideos',
            name='isVoilentThisIteration',
            field=models.BooleanField(default=False),
        ),
    ]
